# Generated by Django 6.0.6 on 2026-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('boot_id', models.CharField(db_index=True, max_length=64)),
                ('ts', models.CharField(max_length=64)),
                ('ts_parsed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event', models.CharField(max_length=16)),
                ('count_in', models.IntegerField(default=0)),
                ('count_out', models.IntegerField(default=0)),
                ('occupancy', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device_id', 'ts_parsed'], name='counts_coun_device__aa78c0_idx')],
            },
        ),
    ]
