# Generated by Django 6.0.6 on 2026-06-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Which device or client this key is for, e.g. 'entrance-01'.", max_length=100)),
                ('prefix', models.CharField(db_index=True, editable=False, max_length=12)),
                ('hashed_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to revoke without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
